spring:
  cache:
    type: caffeine
    cache-names:
      - stockHistory
      - stockQuote
    caffeine:
      spec: maximumSize=500,expireAfterWrite=15m
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
    show-sql: false

application:
  trading:
    default-initial-balance: 10000.00000000
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration-ms: 86400000 # 24 heures
  marketdata:
    alpha-vantage:
      base-url: https://www.alphavantage.co
      api-key: ${ALPHA_VANTAGE_API_KEY:demo}
      connect-timeout-ms: 5000
      read-timeout-ms: 5000
