spring:
  docker:
    compose:
      lifecycle-management: start-and-stop
  datasource:
    # On aligne le port et le nom de la base sur les variables de Docker
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:newtrading}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # AJOUT : Configuration pour la migration Flyway (pom.xml)
  flyway:
    enabled: true
    # Indispensable si vos scripts "./init-scripts" (dans docker-compose) créent déjà des choses
    baseline-on-migrate: true

  jpa:
    hibernate:
      # PARFAIT : on garde validate car Flyway ou Docker gère la structure
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  security:
    jwt:
      # MODIFICATION : Utilisation d'une variable d'environnement avec valeur par défaut
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # Validité de 24 heures en millisecondes
